CREATE TABLE IF NOT EXISTS HUB_CUSTOMER
(
    DVS_HUB_CUSTOMER BIGINT                      NOT NULL,
    C_CUSTKEY        NUMERIC(11, 0)              NOT NULL,
    LDTS             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    RSCR             VARCHAR(256)                NOt NULL
)
    DISTKEY
    (DVS_HUB_CUSTOMER)
    SORTKEY
    (DVS_HUB_CUSTOMER)
;

CREATE TABLE IF NOT EXISTS REF_NATION
(
    NATIONCODE NUMERIC(18, 0)              not null,
    REGIONCODE NUMERIC(18, 0)              not null,
    LDTS       TIMESTAMP WITHOUT TIME ZONE not null,
    RSCR       VARCHAR(256)                NOt NULL,
    N_NAME     CHAR(25),
    N_COMMENT  VARCHAR(152)
) DISTSTYLE ALL;


CREATE TABLE IF NOT EXISTS HUB_ORDER
(
    DVS_HUB_ORDER BIGINT                      NOT NULL,
    O_ORDERKEY    NUMERIC(11, 0)              NOT NULL,
    LDTS          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    RSCR          VARCHAR(256)                NOT NULL
)
    DISTKEY
    (DVS_HUB_ORDER)
    SORTKEY
    (DVS_HUB_ORDER);


CREATE TABLE IF NOT EXISTS REF_REGION
(
    REGIONCODE NUMERIC(18, 0)              not null,
    LDTS       TIMESTAMP WITHOUT TIME ZONE not null,
    RSCR       VARCHAR(256)                NOt NULL,
    R_NAME     CHAR(25),
    R_COMMENT  VARCHAR(152)
) DISTSTYLE ALL;


CREATE TABLE IF NOT EXISTS HUB_PART
(
    DVS_HUB_PART BIGINT                      NOT NULL,
    P_PARTKEY    NUMERIC(11, 0)              NOT NULL,
    LDTS         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    RSCR         VARCHAR(256)                NOT NULL
)
    DISTKEY
    (DVS_HUB_PART)
    SORTKEY
    (DVS_HUB_PART);


CREATE TABLE IF NOT EXISTS HUB_SUPPLIER
(
    DVS_HUB_SUPPLIER BIGINT                      NOT NULL,
    S_SUPPKEY        NUMERIC(11, 0)              NOT NULL,
    LDTS             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    RSCR             VARCHAR(256)                NOT NULL
)
    DISTKEY
    (DVS_HUB_SUPPLIER)
    SORTKEY
    (DVS_HUB_SUPPLIER);


CREATE TABLE IF NOT EXISTS LNK_CUSTOMER_ORDER
(
    DVS_LNK_CUSTOMER_ORDER BIGINT                      NOT NULL,
    DVS_HUB_CUSTOMER       BIGINT,
    DVS_HUB_ORDER          BIGINT,
    LDTS                   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    RSCR                   VARCHAR(256)                NOT NULL
)
    DISTKEY
    (DVS_HUB_ORDER)
    SORTKEY
    (DVS_HUB_ORDER, DVS_HUB_CUSTOMER);


CREATE TABLE IF NOT EXISTS LNK_PART_SUPPLIER
(
    DVS_LNK_PART_SUPPLIER BIGINT                      NOT NULL,
    DVS_HUB_SUPPLIER      BIGINT,
    DVS_HUB_PART          BIGINT,
    LDTS                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    RSCR                  VARCHAR(256)                NOT NULL
)
    DISTKEY
    (DVS_HUB_PART)
    SORTKEY
    (DVS_HUB_PART, DVS_HUB_SUPPLIER);



CREATE TABLE IF NOT EXISTS LNK_LINE_ITEM
(
    DVS_LNK_LINE_ITEM BIGINT                      NOT NULL,
    DVS_HUB_ORDER     BIGINT                      NOT NULL,
    DVS_HUB_SUPPLIER  BIGINT                      NOT NULL,
    DVS_HUB_PART      BIGINT                      NOT NULL,
    L_LINENUMBER      NUMERIC(10, 0),
    LDTS              TIMESTAMP WITHOUT TIME ZONE not null,
    RSCR              VARCHAR(256)                NOt NULL
)
    DISTKEY
    (DVS_HUB_ORDER)
    SORTKEY
    (DVS_HUB_ORDER,DVS_HUB_SUPPLIER, DVS_HUB_PART);


CREATE TABLE IF NOT EXISTS SAT_CUSTOMER
(
    DVS_HUB_CUSTOMER BIGINT                      NOT NULL,
    LDTS             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    C_NAME           VARCHAR(25),
    C_ADDRESS        VARCHAR(40),
    C_PHONE          CHAR(15),
    C_ACCTBAL        NUMERIC(12, 2),
    C_MKTSEGMENT     CHAR(10),
    C_COMMENT        VARCHAR(117),
    NATIONCODE       NUMERIC(18, 0),
    RSCR             VARCHAR(256)                NOT NULL,
    LEDTS            TIMESTAMP WITHOUT TIME ZONE
)
    DISTKEY
    (DVS_HUB_CUSTOMER)
    SORTKEY
    (LDTS);


CREATE TABLE IF NOT EXISTS SAT_LNK_LINE_ITEM
(
    DVS_LNK_LINE_ITEM BIGINT                      NOT NULL,
    LDTS              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    L_QUANTITY        NUMERIC(12, 2),
    L_EXTENDEDPRICE   NUMERIC(12, 2),
    L_DISCOUNT        NUMERIC(12, 2),
    L_TAX             NUMERIC(12, 2),
    L_RETURNFLAG      CHAR(1),
    L_LINESTATUS      CHAR(1),
    L_SHIPDATE        DATE,
    L_COMMITDATE      DATE,
    L_RECEIPTDATE     DATE,
    L_SHIPINSTRUCT    CHAR(25),
    L_SHIPMODE        CHAR(10),
    L_COMMENT         VARCHAR(44),
    RSCR              VARCHAR(256)                NOT NULL,
    LEDTS             TIMESTAMP WITHOUT TIME ZONE
)
    DISTKEY
    (DVS_LNK_LINE_ITEM)
    SORTKEY
    (L_SHIPDATE);


CREATE TABLE IF NOT EXISTS SAT_LNK_PART_SUPPLIER
(
    DVS_LNK_PART_SUPPLIER BIGINT                      NOT NULL,
    LDTS                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PS_AVAILQTY           NUMERIC(10, 0),
    PS_SUPPLYCOST         NUMERIC(12, 2),
    PS_COMMENT            VARCHAR(199),
    RSCR                  VARCHAR(256)                NOT NULL,
    LEDTS                 TIMESTAMP WITHOUT TIME ZONE
)
    DISTKEY
    (DVS_LNK_PART_SUPPLIER);


CREATE TABLE IF NOT EXISTS SAT_ORDER
(
    DVS_HUB_ORDER   BIGINT                      NOT NULL,
    LDTS            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    O_ORDERSTATUS   CHAR(1),
    O_TOTALPRICE    NUMERIC(12, 2),
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK         CHAR(15),
    O_SHIPPRIORITY  NUMERIC(10, 0),
    O_COMMENT       VARCHAR(79),
    RSCR            VARCHAR(256)                NOT NULL,
    LEDTS           TIMESTAMP WITHOUT TIME ZONE
)
    DISTKEY
    (DVS_HUB_ORDER)
    SORTKEY
    (O_ORDERDATE, O_ORDERSTATUS);




CREATE TABLE IF NOT EXISTS SAT_PART
(
    DVS_HUB_PART  BIGINT                      NOT NULL,
    LDTS          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    P_NAME        VARCHAR(55),
    P_MFGR        CHAR(25),
    P_BRAND       CHAR(10),
    P_TYPE        VARCHAR(25),
    P_SIZE        NUMERIC(10, 0),
    P_CONTAINER   CHAR(10),
    P_RETAILPRICE NUMERIC(12, 2),
    P_COMMENT     VARCHAR(23),
    RSCR          VARCHAR(256)                NOT NULL,
    LEDTS         TIMESTAMP WITHOUT TIME ZONE
)
    DISTKEY
    (DVS_HUB_PART)
    SORTKEY
    (DVS_HUB_PART);


CREATE TABLE IF NOT EXISTS SAT_SUPPLIER
(
    DVS_HUB_SUPPLIER BIGINT                      NOT NULL,
    LDTS             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    S_NAME           CHAR(25),
    S_ADDRESS        VARCHAR(40),
    S_PHONE          CHAR(15),
    S_ACCTBAL        NUMERIC(12, 2),
    S_COMMENT        VARCHAR(101),
    NATIONCODE       NUMERIC(18, 0),
    RSCR             VARCHAR(256)                NOT NULL,
    LEDTS            TIMESTAMP WITHOUT TIME ZONE
)
    DISTKEY
    (DVS_HUB_SUPPLIER)
    SORTKEY
    (DVS_HUB_SUPPLIER);

-------------------------------------------------------------------------------

-- Primary Keys
ALTER TABLE HUB_CUSTOMER
    ADD CONSTRAINT PK_HUB_CUSTOMER PRIMARY KEY (DVS_HUB_CUSTOMER);
ALTER TABLE HUB_ORDER
    ADD CONSTRAINT PK_HUB_ORDER PRIMARY KEY (DVS_HUB_ORDER);
ALTER TABLE HUB_PART
    ADD CONSTRAINT PK_HUB_PART PRIMARY KEY (DVS_HUB_PART);
ALTER TABLE HUB_SUPPLIER
    ADD CONSTRAINT PK_HUB_SUPPLIER PRIMARY KEY (DVS_HUB_SUPPLIER);
ALTER TABLE LNK_CUSTOMER_ORDER
    ADD CONSTRAINT PK_LNK_CUSTOMER_ORDER PRIMARY KEY (DVS_LNK_CUSTOMER_ORDER);
ALTER TABLE LNK_LINE_ITEM
    ADD CONSTRAINT OK_LNK_LINE_ITEM PRIMARY KEY (DVS_LNK_LINE_ITEM);
ALTER TABLE LNK_PART_SUPPLIER
    ADD CONSTRAINT PK_LNK_PART_SUPPLIER PRIMARY KEY (DVS_LNK_PART_SUPPLIER);
ALTER TABLE SAT_PART
    ADD CONSTRAINT PK_SAT_PART PRIMARY KEY (LDTS, DVS_HUB_PART);
ALTER TABLE SAT_ORDER
    ADD CONSTRAINT PK_SAT_ORDER PRIMARY KEY (DVS_HUB_ORDER, LDTS);
ALTER TABLE SAT_LNK_PART_SUPPLIER
    ADD CONSTRAINT PK_SAT_LNK_PART_SUPPLIER PRIMARY KEY (LDTS, DVS_LNK_PART_SUPPLIER);
ALTER TABLE SAT_LNK_LINE_ITEM
    ADD CONSTRAINT PK_SAT_LNK_LINE_ITEM PRIMARY KEY (DVS_LNK_LINE_ITEM, LDTS);
ALTER TABLE SAT_CUSTOMER
    ADD CONSTRAINT OK_SAT_CUSTOMER PRIMARY KEY (DVS_HUB_CUSTOMER, LDTS);
ALTER TABLE SAT_SUPPLIER
    ADD CONSTRAINT PK_SAT_SUPPLIER PRIMARY KEY (LDTS, DVS_HUB_SUPPLIER);
ALTER TABLE REF_NATION
    ADD CONSTRAINT PK_REF_NATION PRIMARY KEY (NATIONCODE);
ALTER TABLE REF_REGION
    ADD CONSTRAINT PK_REF_REGION PRIMARY KEY (REGIONCODE);